config/routes.rb
Rails.application.routes.draw do
  
  resources :comments

devise_for :users
  
  resources :magazines do 
    member do
      get "articles"
    end
  end  
  root 'magazines#index'
   resources :articles, :except => [:new] do
    member do
      get "new",:as => "new"
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :magazine
  has_many :comments
  validates :title ,:presence => { :message => "can not be blank." },length: { in: 1..30 }
  #validates :author ,:presence => { :message => "can not be blank." },length: { in: 1..30 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
  has_ancestry
  validates :user_id, :body,:article_id, :presence => true
end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
  belongs_to :user
  has_many :articles
  validates :title ,:presence => { :message => "Please Enter the title." },length: { in: 1..50 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :magazine
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comment = Comment.new(:article_id => @article.id) if @article.present?    
    @comments = @article.comments.order("created_at") if @article.present?
  end

  # GET /articles/new
  def new
    @magazine = Magazine.find(params[:id])
    @article = @magazine.articles.new   
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
     @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
   
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
   

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
       params.require(:article).permit(:title, :magazine_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]


  #def index
   # @comments = Comment.all
   # respond_with(@comments)
  #end

  #def show
   # respond_with(@comment)
  #end

  def new
    @comment = Comment.new(:parent_id => params[:parent_id],:article_id => params[:article_id])
    #@comment = Comment.new
    #respond_with(@comment)
  end

  #def edit
  #end

  def create
    @comment = current_user.comments.new(comment_params)
    respond_to do |format|
      if @comment.save
        @article = Article.find_by_id(params[:comment][:article_id])
        @comments = @article.comments.order("created_at") if @article.present?
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js{}
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.js{}
      end
    end
  end

  #def update
   # @comment.update(comment_params)
   # respond_with(@comment)
  #end

  def destroy
    @comment.destroy
    respond_to do |format|
      @article = Article.find_by_id(params[:article_id])
      @comments = @article.comments.order("created_at") if @article.present?
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
      format.js {}
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
       params.require(:comment).permit(:body,:article_id,:parent_id)
    end
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  before_action :set_magazine, only: [:show, :edit, :update, :destroy, :articles]

  # GET /magazines
  # GET /magazines.json
  def index
    @magazines = Magazine.all
  end

  # GET /magazines/1
  # GET /magazines/1.json
  def show
  end

  # GET /magazines/new
  def new
    @magazine = Magazine.new
  end

  # GET /magazines/1/edit
  def edit
  end

  # POST /magazines
  # POST /magazines.json
  def create
    @magazine = Magazine.new(magazine_params)

    respond_to do |format|
      if @magazine.save
        format.html { redirect_to @magazine, notice: 'Magazine was successfully created.' }
        format.json { render :show, status: :created, location: @magazine }
      else
        format.html { render :new }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magazines/1
  # PATCH/PUT /magazines/1.json
  def update
    respond_to do |format|
      if @magazine.update(magazine_params)
        format.html { redirect_to @magazine, notice: 'Magazine was successfully updated.' }
        format.json { render :show, status: :ok, location: @magazine }
      else
        format.html { render :edit }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazines/1
  # DELETE /magazines/1.json
  def destroy
    @magazine.destroy
    respond_to do |format|
      format.html { redirect_to magazines_url, notice: 'Magazine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def articles
   if @magazine.present?
    @articles = @magazine.articles
   end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magazine
      @magazine = Magazine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def magazine_params
      params.require(:magazine).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      
      render(comment) + content_tag(:ul, nested_comments(sub_comments), :class => "nested_comments")
    end.join.html_safe
  end
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 <%= f.text_field :title, :class=> "form-control" %>
   <%= f.hidden_field :magazine_id %><br>
    <%= f.submit %>
  
<% end %>

app/views/articles/_show_comments.html.erb
<div class="tree ">
  <ul>
    <%= nested_comments @comments.arrange(:order => :created_at) %>
  </ul>
</div>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
      <td><%= link_to article.title, article %></td>
        <td><%= link_to 'Show', article %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<% if @article.present? %>
    <div class="col-lg-12">
      <div>
        <h2 class="text-center"><%= @article.title %>
        <% if user_signed_in? %>
        <p><%= link_to 'Edit Article', edit_article_path(@article),:class=>"btn btn-default pull-right" %></p></h2>
        <p>
        <% end %>
                 
        
        <p>
          <strong>Magazine:</strong>
          <%= @article.magazine.title %>
        </p>
        
      </div>
    </div>
    <div class="col-lg-12" id="comment_div">
      <%= render "show_comments" unless @comments.empty? %>
    </div>
    <div class="col-lg-12">
    <% if user_signed_in? %>
      <%= link_to "Comment Article", new_comment_path(:article_id => @article.id),:class => "btn btn-default", :remote => "true" %>
      <% end %>
      <div class="modal fade comment_modal" id="comment_modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="gridSystemModalLabel"><%= "#{@article.title}" %></h4>
            </div>
            <div class="modal-body">
              <div class="container-fluid">
                <div class="row" id="comment_form">
                  <%= render "comments/form" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
<% else %>
    <p class="alert alert-error"><%= "Article Not Found" %></p>
<% end %>

app/views/comments/_comment.html.erb
<li>
  <span><i class="icon-folder-open"></i> <%= comment.body %></span> 
<% if user_signed_in? %>
  <%= link_to "Reply", new_comment_path(:parent_id => comment,:article_id => comment.article_id), :remote => "true" %>
  <% if comment.descendants.count <= 0 %>
      <% if current_user.id==comment.user_id %>
        | <%= link_to "Destroy", comment_path(:id =>  comment.id,:article_id => comment.article_id), :confirm => "Are you sure?", :remote => "true",:method => :delete %>
      <% end %>  
  <% end %>
  <% end %>
</li>

app/views/comments/_form.html.erb
<%=form_for @comment, :html => {:class=>"form-inline",:remote => true } do |f| %>
  <%= f.hidden_field :parent_id %>
  <%= f.hidden_field :article_id %>
  <div class="form-group">
    <div class="input-group">
      <div class="input-group-addon">Comment</div>
      <%= f.text_field :body, :class => "form-control" %>
      </div>
  </div>
  <%= f.submit "Post Comment",:class=>"btn btn-primary" %>
<% end %> 

<!-- SQuare Labs
<!-- GIT,AWS

app/views/comments/create.js.erb
<% if @comments.present? %>
$("#comment_div").html("<%= j render 'articles/show_comments' %>");
$('#comment_modal').modal('hide');
<% else %>
alert("<%= @comment.errors.full_messages.join(",").html_safe %>");
$('#comment_modal').modal('hide');
<% end %>

app/views/comments/destroy.js.erb
$("#comment_div").html("<%= j render 'articles/show_comments' %>");

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/new.js.erb
$("#comment_form").html("<%= j render 'form' %>");
$('#comment_modal').modal('show');

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PS Magazine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default">
<div class="container">

<div class="navbar-header">
<%= link_to "Magazine List", root_path, class: "navbar-brand" %>

</div>
<div class="col-lg-12">
<%= link_to " Sign Up |", new_user_registration_path, class: "pull-right" %> 
<% if user_signed_in? %>
  <%= link_to " Sign Out | ", destroy_user_session_path, method: :delete, class: "pull-right" %>
<% else %>
<%= link_to "Log in | ", new_user_session_path, class: "pull-right" %>
<% end %> 
<% if user_signed_in? %>
  <%= link_to "New Magazine | ", new_magazine_path, class: "pull-right" %>
  <% end %>
</div>

</div>
</div>
<!--
<p class="notice"><%= notice %></p> -->
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/magazines/_form.html.erb
<%= simple_form_for @magazine do |f| %>
  <% if @magazine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@magazine.errors.count, "error") %> prohibited this magazine from being saved:</h2>

      <ul>
      <% @magazine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/magazines/articles.html.erb
<br/>
<div>
  <!-- Default panel contents -->
  <div>Articles</div>
  <div class="panel-body">
    <% if @articles.present? %>
      <ul>
        <% @articles.each do |article|%>
        <li><%= link_to article.title, article %></li>
         
        <% end %>
      </ul>
    <% else %>
      <p> No Articles Found. </p>
    <% end%>
  </div>
  <% if user_signed_in? %>
 <%= link_to "New Article", new_article_path(@magazine) %>
 <% end%>
</div>

app/views/magazines/edit.html.erb
<h1>Editing Magazine</h1>

<%= render 'form' %>

<%= link_to 'Show', @magazine %> |
<%= link_to 'Back', magazines_path %>

app/views/magazines/index.html.erb
<p id="notice"><%= notice %></p>

<% @magazines.each do |magazine| %>
<h2><%= magazine.title %></h2>

<%= link_to 'View Details', magazine, class: "btn btn-default" %>

<%= link_to 'Articles', articles_magazine_path(magazine), class: "btn btn-default" %>
<% end %>

app/views/magazines/new.html.erb
<h1>New Magazine</h1>

<%= render 'form' %>

<%= link_to 'Back', magazines_path %>

app/views/magazines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @magazine.title %>
</p>
<% if user_signed_in? %>
<%= link_to 'Edit', edit_magazine_path(@magazine) %> |
<%end%> 
<%= link_to 'Back', magazines_path %> 